### PR TITLE
UpdateDBService: fix call on possibly null object

### PR DESCRIPTION
**Pull request by bestvibes**
This error kept sending NPEs on every update.

### CODE REVIEW

**Comment by Zhouball** [comment]
Sorry; we're working on a quickfix for the new website UCLA just pushed. We hope to get this fixed soon!

**Comment by bestvibes** [comment]
Thanks! Just so you know this doesn't have to do with that, I've been
getting this error for months, it's just a general logic fix :) Unless
you're overhauling the code I think this is still necessary.

**Comment by preethamrn** [comment]
Has this error prevented you from using the app? It shouldn't be a problem and hasn't affected me. Regardless, we'll probably look into it and this is fine for a temporary fix.

**Comment by bestvibes** [comment]
No, it's a silent error since its in the service. And maybe the issue is
occurring because the doinbackground is synchronized? Just a hunch.

**Comment by bestvibes** [comment]
Here's the error :

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean
java.util.ArrayList.isEmpty()' on a null object reference
    at
zhou.allen.bruinmenu.UpdateDBService$UpdateDB.onPostExecute(UpdateDBService.java:224)
    at
zhou.allen.bruinmenu.UpdateDBService$UpdateDB.onPostExecute(UpdateDBService.java:73)
    at android.os.AsyncTask.finish(AsyncTask.java:636)
    at android.os.AsyncTask.access$500(AsyncTask.java:177)
    at
android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5300)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

**Pull request merged**
